### PR TITLE
Taking on role as communication and education community role

### PR DESCRIPTION
**Pull request by hayesla**
### Description
Now that @drsophiemurray has stepped down from the Communication and Education Lead as the Community Role, I'm more than happy to fill this role as discussed with @Cadair 

Hope that works for everyone else!

### CODE REVIEW

**Review by Cadair — APPROVED** [review]
:partying_face: Thank you!

**Comment by drsophiemurray** [comment]
Yay! 🥳

**Comment by hayesla** [comment]
whats the best way to upload photo?

**Comment by Cadair** [comment]
Think they are all just in this repo?

**Comment by hayesla** [comment]
ah yeah, I'll add one now

**Review by Cadair — APPROVED** [review]

**Review by wtbarnes — APPROVED** [review]

**Pull request merged**
