### PR TITLE
README and Cleanup

### LINKED ISSUE #126: Document the fact the website is now deployed using Netlify

### PR DESCRIPTION
**Pull request by Cadair**
fixes #126

### CODE REVIEW

**Comment by nabobalis** [comment]
I WAS DOING THIS

**Comment by Cadair** [comment]
Travis is running but not reporting?!

**Comment by nabobalis** [comment]
COuld take a bit for the branch name change for travis to notice?

**Comment by Cadair** [comment]
:woman_shrugging: good enough for now

**Pull request merged**
