### PR TITLE
Adding Bin Chen to the SunPy Project page

### PR DESCRIPTION
**Pull request by binchensun**

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks @binchensun but the image is missing. The rest renders perfectly.

**Comment by nabobalis** [comment]
The image is a bit large but It ain't worth worrying about for this PR. Thanks @binchensun

**Comment by binchensun** [comment]
Thank you for your help!

**Comment by ehsteve** [comment]
@nabobalis how did this get approved?! @binchensun's photo is not a circle!!!!!

**Comment by nabobalis** [comment]
Check my previous comments. I don't want them dealing with it themselves. That's for us to fix. Which we will

**Pull request merged**
