### PR TITLE
Improve help page

### PR DESCRIPTION
**Pull request by dstansby**
As suggested by @jmbhughes at the coordination meeting, this should simplify and improve the help page

### CODE REVIEW

**Comment by nabobalis** [comment]
If we arent going to use the supporting.md, we should also remove it from the .github repo.

**Comment by dstansby** [comment]
I'm fine with that, but wasn't sure if it was there for a reason? Is it a file that GH recognises?

**Comment by nabobalis** [comment]
I thought it was, which was why it was moved there but for the life of me, I can't find where its used anymore.

**Comment by dstansby** [comment]
This should be good to review

**Comment by nabobalis** [comment]
Github is not handling the file change as I can't make suggestions.

Docs -> Documentation, just worried docs is too informal or unclear, to people who are new or without english as a first language.

**Comment by nabobalis** [comment]
Rendered version is here: https://deploy-preview-327--sunpy.netlify.app/help

**Comment by Cadair** [comment]
I like the intent and the direction here, but as it presents at the moment I don't really like the style.

Some thoughts:

Maybe it would be worth adding icons or logos to these things?

Can we make the whole tile clickable rather than links inside the tile?

Can we reduce the amount of text in the documentation one, it's very hard to read so much text in such a small box?

Can we get rid of the side bar if we aren't going to use it?

**Comment by dstansby** [comment]
> Maybe it would be worth adding icons or logos to these things?

Would love to do this, but not sure how. I'll look into this a bit more.

> Can we make the whole tile clickable rather than links inside the tile?

Done

> Can we reduce the amount of text in the documentation one, it's very hard to read so much text in such a small box?

Do you have any suggestions? I agree with you, but not sure how to convey the concept of n > 1 documentation websites with less text.

> Can we get rid of the side bar if we aren't going to use it?

Done

Getting there, but there's still lots of things to be done to make it pretty so I'll mark as draft, but thanks for all the ideas and review so far!

**Comment by dstansby** [comment]
I'm also wondering if this is getting so minimal it needs to live on another page? (the home page?)

**Comment by nabobalis** [comment]
Did we ever decide what to do about the help page?

**Review by nabobalis — APPROVED** [review]

**Pull request merged**
