### PR TITLE
added submodule

### PR DESCRIPTION
**Pull request by nabobalis**

### CODE REVIEW

**Comment by Cadair** [comment]
also the CoC?

**Comment by nabobalis** [comment]
Not sure I like the module name.

**Comment by nabobalis** [comment]
Renders ok.

**Comment by nabobalis** [comment]
https://github.com/sunpy/sunpy-sphinx-theme/pull/122/ to add the COC to the dropdown.

**Review by kakirastern — APPROVED** [review]

**Review by Cadair — APPROVED** [review]

**Pull request merged**
