### PR TITLE
Blog post on using coordinates to model loops

### PR DESCRIPTION
**Pull request by wtbarnes**
This blog post is a tutorial for using the `sunpy.coordinates` module for modeling loops on the Sun. Any feedback (on the code and/or text) is greatly appreciated!

### CODE REVIEW

**Comment by Cadair** [comment]
Oh man that renders lovely: https://deploy-preview-133--sunpy.netlify.com/posts/2018/2018-07-21-coronal-loop-coordinates.html

**Comment by Cadair** [comment]
The only comment with this is that some of the code in the cells is too wide for the width of the code cells. We should probably try and make the code cells wider?

**Comment by Cadair** [comment]
Also is there a "download this notebook" link we can build in somewhere?

**Comment by wtbarnes** [comment]
Oh true. That box on the left is pretty wide. Maybe making that a bit more narrow would help.

**Comment by nabobalis** [comment]
Maybe? We can change the CSS tho.

**Comment by Cadair** [comment]
We could also CSS out the input and output cell markers? That gives us quite a bit more space?

**Comment by nabobalis** [comment]
Probably? I don't think we touch those normally in the CSS.

**Comment by nabobalis** [comment]
Is the problem the code cells have scroll bars?

**Comment by wtbarnes** [comment]
Could do. That may involve a PR to nbsphinx

**Comment by Cadair** [comment]
Also @wtbarnes I would put your bio at the top.

**Comment by Cadair** [comment]
> That may involve a PR to nbsphinx

We could just do it in the sunpy theme I would think.

**Comment by wtbarnes** [comment]
Feels like it might be too distracting at the top

**Comment by wtbarnes** [comment]
To strip out the `In[]`,`Out[]` tags, I think you might have intervene at the nbconvert step which is controlled by nbsphinx... I may be wrong here.

**Comment by nabobalis** [comment]
Could we not somehow use these? 

https://github.com/jupyter/nbconvert-examples/tree/master/latex_cell_style

**Comment by Cadair** [comment]
I think sunpy/sunpy-sphinx-theme#58 should do the job

**Comment by wtbarnes** [comment]
Sure, but I think the issue is getting nbsphinx to use your custom template (i.e. `tpl` file). See spatialaudio/nbsphinx#132. Currently, doesn't look like the nbsphinx supports custom templates.

**Comment by wtbarnes** [comment]
image

**Comment by wtbarnes** [comment]
@Cadair nice

**Comment by Cadair** [comment]
How much control does nbsphinx give you over the colour scheme of the cells? I don't like the lack of contrast in the current ones, not great for accessibility etc.

**Comment by wtbarnes** [comment]
I think it just depends on the syntax highlighter you're using.

**Comment by wtbarnes** [comment]
You can set the pygments style in the `theme.conf` file of the theme

**Comment by Cadair** [comment]
Nabil you wanna roll out a theme update before or after merging this?

**Comment by nabobalis** [comment]
Err, either?

**Comment by Cadair** [comment]
I leave it up to you.

**Comment by nabobalis** [comment]
Done. You can revert it back to normal now.

**Comment by wtbarnes** [comment]
🎉

**Pull request merged**
