### PR TITLE
replaceed rawfiles

### LINKED ISSUE #191: Website build is broken
It looks like the rawfiles extension is out of date, we could vendor in https://gist.github.com/troter/3120580

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes #191

### CODE REVIEW

**Comment by Cadair** [comment]
can we remove the sphinx pin in this PR as well?

**Comment by Cadair** [comment]
lol ok

**Comment by nabobalis** [comment]
The pin?

**Comment by Cadair** [comment]
didn't we pin sphinx to fix the build?

**Comment by nabobalis** [comment]
No?

**Comment by Cadair** [comment]
oh ok.

**Comment by nabobalis** [comment]
If you we did, I didn't do it. I thought we just let the build die.

**Pull request merged**
