### PR TITLE
added link to board meeting minutes on website

### LINKED ISSUE #195: Add link to Board meeting minutes on website
It would be nice to have a link to the [meeting minutes](https://github.com/sunpy/sunpy/wiki/Home%3A-Organization-Information#minutes-of-sunpy-board-meetings) on the [project page](https://sunpy.org/team.html#sunpy-board), to increase their visibility.

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes #195

### CODE REVIEW

**Comment by nabobalis** [comment]
Hi @iamrajiv! Thank you for the pull request but it seems you have also committed the build files. The fact it isn't gitignored is an oversight on our part. Could you `git rm -f ` them please?

**Comment by iamrajiv** [comment]
@nabobalis I have removed the `_build` files but I don't understand If I had removed the `_build` files the code what I had added also got deleted then how it will work. Can you please help me with this?

**Comment by nabobalis** [comment]
@iamrajiv I would suggest by undoing the last two commits by doing 
```
git reset HEAD~2
``` 
then 
```
git add <path to file you changed>
git commit -m "<message>"
```
then
```
git push --force
```

That should fix it hopefully.

**Comment by iamrajiv** [comment]
@nabobalis I have committed the files is this correct?

**Comment by nabobalis** [comment]
Unfortunately not. We don't commit anything under the `_build` directly into the repo. The entire website source is RST files which are you have to edit. For example the team page on the website is sourced from this RST file: https://github.com/sunpy/sunpy.org/blob/master/team.rst

**Comment by iamrajiv** [comment]
oh sorry, @nabobalis  I got it means I just have to edit the `team.rst` files and to check the output I have to use `make html` which will generate the `_build` files and before committing I have the delete the `_build` files. Am I right

**Comment by nabobalis** [comment]
Yes that is correct.

**Comment by iamrajiv** [comment]
@nabobalis can you please take a look

**Comment by nabobalis** [comment]
You would also need to remove:

`CITATION.rst`
`exts/__pycache__/cards.cpython-37.pyc`
`exts/__pycache__/rawfiles.cpython-37.pyc`

otherwise it look good to me.

**Comment by nabobalis** [comment]
Can you also add those files and directories into the `.gitignore` file? Hopefully will prevent this from happening again.

**Comment by iamrajiv** [comment]
@nabobalis sorry for the inconvenience I am closing this PR because I got some branch conflict

**Comment by nabobalis** [comment]
Thats fine.

**Pull request closed without merging**
