### PR TITLE
fix for Bin Chen photo

### PR DESCRIPTION
**Pull request by ehsteve**

### CODE REVIEW

**Comment by ehsteve** [comment]
First time using content-aware fill in photoshop...pretty cool. @binchensun

**Comment by nabobalis** [comment]
In the future you will want a a script

**Comment by ehsteve** [comment]
@nabobalis you can also do it with some CSS so no need to actually edit the photo.

**Comment by nabobalis** [comment]
Well if you know how, we should set the css

**Comment by binchensun** [comment]
Sorry I was not aware that the photo has to be cut into the exact shape. I could have cut it in Photoshop. Thank you for fixing it, Steven! @ehsteve

**Comment by ehsteve** [comment]
@binchensun no problem! @nabobalis should have made a thorough review :P

**Comment by nabobalis** [comment]
I don't think that expecting a person to have access to photoshop is a good idea. 

So either we fix it via the CSS as you suggested (Gonna need to see that css code tho) or we have a script that we can just run on any face images.

**Pull request merged**
